### PR TITLE
Ue5 Initial Support via alonfaraj

### PR DESCRIPTION
**Pull request by xxEoD2242**
Mimics work done in Airsim: [AirSim PR # 4672](https://github.com/microsoft/AirSim/pull/4672)

Credit to @alonfaraj

Fixes: #    

## TODO:
- [x] Validate AirSim Multirotor pawn
- [x] Validate Multirotor API methods in Python
- [x] Validate vehicle API methods in Python
- [ ] Validate multirotor API methods in C++
- [ ] Validate vehicle API methods in C++
- [ ] Validate utilizing PX4/Ardupilot
- [ ] Validate keyboard controls with Vehicle

### CODE REVIEW

**Comment by noncomposmentis** [comment]
Is this only functional with the car APIs or did you just happen to not have to modify any of those files?

**Comment by xxEoD2242** [comment]
Correct, only the car is supported. Work for Multirotor is ongoing

**Comment by alonfaraj** [comment]
Hey @noncomposmentis @xxEoD2242, 
Actually multirotor works out of the box.
I have updated the original PR with an example video using the hello_drone.py.

**Comment by xxEoD2242** [comment]
@noncomposmentis Awesome! Thank you!

I will reflect that in the PR. I still want to verify PX4/Ardupilot integration and a few other API calls to make sure but will not that as such.

**Comment by xxEoD2242** [comment]
Leaving notes here:

UE5 requires a .NET Framework 3.0.X install, which can be done through VS 22 installer.

Still TBD on whether this works on Linux but issues with packaging are currently occurring.

**Comment by xxEoD2242** [comment]
@alonfaraj Did you regenerate the animation .uasset file in the Unreal/Plugins/AirSim/Content folder? I tried to load the car and so did someone else is #17 and the animation files were corrupted since they are PhysX based.

**Comment by alonfaraj** [comment]
@xxEoD2242 Did you download the files from the link provided in the PR?
You should override the original files

**Pull request merged**
